// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OauthStore is an autogenerated mock type for the OauthStore type
type OauthStore struct {
	mock.Mock
}

// GetToken provides a mock function with given fields: authCookie
func (_m *OauthStore) GetToken(authCookie string) (interface{}, error) {
	ret := _m.Called(authCookie)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(authCookie)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(authCookie)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetToken provides a mock function with given fields: authToken
func (_m *OauthStore) SetToken(authToken interface{}) (string, error) {
	ret := _m.Called(authToken)

	var r0 string
	if rf, ok := ret.Get(0).(func(interface{}) string); ok {
		r0 = rf(authToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(authToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
