// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/sepuka/vkbotserver/domain"
	mock "github.com/stretchr/testify/mock"
)

// SessionsRepository is an autogenerated mock type for the SessionsRepository type
type SessionsRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: user, token
func (_m *SessionsRepository) Create(user *domain.User, token string) error {
	ret := _m.Called(user, token)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.User, string) error); ok {
		r0 = rf(user, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
