[[constraint]]
  name = "go.uber.org/zap"
  version = "1.16.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.7.0"

[[constraint]]
  name = "github.com/mailru/easyjson"
  version = "0.7.7"