// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Rnder is an autogenerated mock type for the Rnder type
type Rnder struct {
	mock.Mock
}

// Rnd provides a mock function with given fields:
func (_m Rnder) Rnd() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}
